#!/bin/bash
set -euo pipefail

CONFIG_DIR="${SRCROOT}/Config"
SECRETS_FILE="${CONFIG_DIR}/Secrets.env"
OUTPUT_FILE="${SRCROOT}/App/GeneratedSecrets.swift"

API_KEY=""
BASE_URL=""
MODEL="deepseek-v4-flash"
VISION_MODEL="qwen-vl-plus"

if [[ -f "$SECRETS_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$SECRETS_FILE"
  set +a
  API_KEY="${DASHSCOPE_API_KEY:-}"
  BASE_URL="${DASHSCOPE_BASE_URL:-}"
  MODEL="${LLM_MODEL:-deepseek-v4-flash}"
  VISION_MODEL="${VISION_MODEL:-qwen-vl-plus}"
else
  echo "warning: ${SECRETS_FILE} not found — copy Config/Secrets.env.example to Config/Secrets.env"
fi

escape_swift_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<EOF
// Auto-generated by Scripts/generate-secrets.sh — DO NOT EDIT
import Foundation

enum AppSecrets {
    static let dashscopeAPIKey = "$(escape_swift_string "$API_KEY")"
    static let dashscopeBaseURL = "$(escape_swift_string "$BASE_URL")"
    static let llmModel = "$(escape_swift_string "$MODEL")"
    static let visionModel = "$(escape_swift_string "$VISION_MODEL")"

    static var isConfigured: Bool {
        !dashscopeAPIKey.isEmpty && !dashscopeBaseURL.isEmpty
    }

    static var hasVisionModel: Bool {
        !visionModel.isEmpty
    }
}
EOF
